# Default values for drinkn.
image:
  tag: "sha-3b8fbc0"

replicas: "2"

fqdn: pils.oscarr.nl

pr:
  enabled: false
  number: 9999
  ref: main
  status:
    - PreSync
    - PostSync
    - SyncFail
    - PostDelete
